Repository collab-project/videojs-record, pull requests merged in 2019-07, with the labels that each got.

#384 fix RecordRTC.MediaStreamRecorder import when using timeSlice option
  CHANGES.md
  README.md
  bower.json
  build-config/fragments/dev.js
  examples/timeslice.html
  examples/upload/simple.html
  examples/upload/websocket.html
  examples/upload/websocket.js
  package-lock.json
  package.json
  src/js/engine/record-rtc.js
  src/js/videojs.record.js
Labels: bugfix

#386 Support for optional plugin settings
  CHANGES.md
  README.md
  examples/plugins/audio-only-mp3.html
  examples/plugins/audio-only-opus.html
  examples/plugins/video-only-webm-wasm.html
  package-lock.json
  package.json
  src/js/defaults.js
  src/js/engine/record-rtc.js
  src/js/plugins/lamejs-plugin.js
  src/js/plugins/libvorbis-plugin.js
  src/js/plugins/opus-recorder-plugin.js
  src/js/plugins/recorderjs-plugin.js
  src/js/plugins/vmsg-plugin.js
  src/js/plugins/webm-wasm-plugin.js
  src/js/videojs.record.js
  test/defaults.spec.js
Labels: enhancement, plugins

#201 ffmpeg.js plugin
  CHANGES.md
  README.md
  examples/plugins/audio-only-ffmpegjs.html
  examples/plugins/video-only-ebml.html
  karma.conf.js
  package-lock.json
  package.json
  src/js/defaults.js
  src/js/engine/convert-engine.js
  src/js/engine/engine-loader.js
  src/js/event.js
  src/js/plugins/ffmpegjs-plugin.js
  src/js/plugins/ts-ebml-plugin.js
  src/js/videojs.record.js
  test/defaults.spec.js
  test/engine/convert-engine.spec.js
  test/engine/record-engine.spec.js
  test/plugins/ffmpegjs-plugin.spec.js
  test/test-helpers.js
Labels: enhancement, plugins

#385 Support for capturing screen + audio
  CHANGES.md
  README.md
  examples/audio-screen.html
  src/css/_icons.scss
  src/css/components/device-button.scss
  src/fonts/icons.json
  src/fonts/videojs-record.svg
  src/js/engine/record-mode.js
  src/js/engine/record-rtc.js
  src/js/videojs.record.js
  test/engine/record-mode.spec.js
  test/test-helpers.js
  test/videojs.record.spec.js
Labels: enhancement

#388 support video.js picture-in-picture API (introduced in video.js 7.6.0)
  CHANGES.md
  examples/picture-in-picture.html
  src/js/utils/compare-version.js
  src/js/videojs.record.js
  test/utils/compare-version.spec.js
Labels: enhancement
