Repository collab-project/videojs-record, pull requests merged in 2024-02, with the labels that each got.

#704 doc: use wavesurfer 6.x in examples
  .github/workflows/main.yml
  LICENSE
  docs/demo/animated-gif.html
  docs/demo/audio-only-ffmpegjs.html
  docs/demo/audio-only-lamejs.html
  docs/demo/audio-only-mp3.html
  docs/demo/audio-only-ogg.html
  docs/demo/audio-only-opus-media-recorder.html
  docs/demo/audio-only-opus.html
  docs/demo/audio-only-recorderjs.html
  docs/demo/audio-only.html
  docs/demo/audio-screen.html
  docs/demo/audio-video.html
  docs/demo/change-audio-input.html
  docs/demo/change-audio-output.html
  docs/demo/change-video-input.html
  docs/demo/enumerate-devices.html
  docs/demo/hot-keys.html
  docs/demo/image-only.html
  docs/demo/multi.html
  docs/demo/picture-in-picture.html
  docs/demo/react/index.html
  docs/demo/screen-only.html
  docs/demo/timeslice.html
  docs/demo/video-only-ebml.html
  docs/demo/video-only-ffmpegwasm.html
  docs/demo/video-only-webm-wasm.html
  docs/demo/video-only.html
  docs/install.md
  docs/tools/update-videojs.js
  package-lock.json
  package.json
Labels: documentation, ci

#706 ci: replace appveyor with gh actions
  .github/workflows/main.yml
  appveyor.yml
Labels: ci

#708 ffmpeg.wasm plugin: add support for v0.12.x
  CHANGES.md
  docs/demo/animated-gif.html
  docs/demo/audio-only-ffmpegjs.html
  docs/demo/audio-only-lamejs.html
  docs/demo/audio-only-mp3.html
  docs/demo/audio-only-ogg.html
  docs/demo/audio-only-opus-media-recorder.html
  docs/demo/audio-only-opus.html
  docs/demo/audio-only-recorderjs.html
  docs/demo/audio-only.html
  docs/demo/audio-screen.html
  docs/demo/audio-video.html
  docs/demo/change-audio-input.html
  docs/demo/change-audio-output.html
  docs/demo/change-video-input.html
  docs/demo/enumerate-devices.html
  docs/demo/hot-keys.html
  docs/demo/image-only.html
  docs/demo/multi.html
  docs/demo/picture-in-picture.html
  docs/demo/react/index.html
  docs/demo/screen-only.html
  docs/demo/timeslice.html
  docs/demo/video-only-ebml.html
  docs/demo/video-only-ffmpegwasm.html
  docs/demo/video-only-webm-wasm.html
  docs/demo/video-only.html
  docs/options.md
  docs/package-lock.json
  docs/package.json
  docs/plugins/ffmpeg.wasm.md
  docs/tools/update-videojs.js
  examples/plugins/video-only-ffmpegwasm.html
  package-lock.json
  package.json
  src/js/plugins/ffmpeg-wasm-plugin.js
Labels: plugins

#677 Update options documentation to match default in code for videoMimeType
  docs/options.md
Labels: documentation
